{
    'name': 'Water Meter Readings',
    'version': '19.0.27.0.0',
    'summary': 'Registro de lecturas de contadores de agua',
    'category': 'Tools',
    'author': 'Toni',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'external_dependencies': {'python': ['openpyxl', 'pymysql']},
    'assets': {
        'web.assets_backend': [
            'water_meter_reading/static/src/js/camera_image_field.js',
            'water_meter_reading/static/src/xml/camera_image_field.xml',
            'water_meter_reading/static/src/scss/mobile_reading.scss',
        ],
    },
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/res_users_views.xml',
        'views/water_meter_views.xml',
        'views/mobile_reading_views.xml',
        'views/water_period_views.xml',
        'views/meter_import_views.xml',
        'views/missing_route_views.xml',
        'views/gtb_update_views.xml',
        'views/mariadb_settings_views.xml',
        'views/mariadb_connection_views.xml',
        'data/sequence_data.xml',
    ],
    'installable': True,
    'application': True,
}
