{
    'name': 'Water Meter Readings',
    'version': '19.0.3.2.0',
    'summary': 'Registro de lecturas de contadores de agua',
    'category': 'Tools',
    'author': 'Toni',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'external_dependencies': {'python': ['openpyxl']},
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/res_users_views.xml',
        'views/water_meter_views.xml',
        'views/water_period_views.xml',
        'views/meter_import_views.xml',
        'data/sequence_data.xml',
    ],
    'installable': True,
    'application': True,
}
